# This script can be used to derive company-specific sector shares for energy
# companies that are active in two or more of the following PACTA sectors:
# Coal, Oil & Gas, Power.
# The sector splits are calculated based on a common unit of economic activity,
# million tons of oil equivalent (mtoe). A number of transformation steps must
# be made to arrive at this common unit for all three energy sectors.
# For the Oil & Gas and the Coal sectors, the transformation is rather straight
# forward, as both are already given in terms of primary energy. This means a
# simple conversion factor can be applied.
# For Power Generation, the steps are more complicated. Power generation is
# given in terms of MWh of electricity generated. This needs to be converted to
# mtoe using a conversion factor as in the other cases. Additionally, we need to
# consider that the process of generating electricity from a primary energy
# input leads to losses of primary energy in terms of heat in some technologies.
# The amount of primary energy lost to heat differs by technology and is
# generally relevant in power generation through heat or combustion, but not all
# other ways of generating electricity.
# We therefore have to divide the electricity generated by an efficiency factor
# specific to each technology to arrive at a primary energy equivalent for power
# generation.

# load packages----
devtools::load_all()

library(dotenv)
library(janitor)
library(r2dii.analysis)
library(r2dii.data)
library(r2dii.match)
library(r2dii.plot)
library(readr)
library(readxl)
library(rlang)
library(tidyverse)
library(vroom)

dotenv::load_dot_env()

# get sector split for energy companies----

# TODO: add test files to read in case not all required inputs are provided correctly

## set up paths----
input_path_split <- file.path(Sys.getenv("DIR_SPLIT_COMPANY_ID"), Sys.getenv("FILENAME_SPLIT_COMPANY_ID"))
input_path_advanced_company_indicators <- file.path(Sys.getenv("DIR_ADVANCED_COMPANY_INDICATORS"), Sys.getenv("FILENAME_ADVANCED_COMPANY_INDICATORS"))
input_path_matched <- Sys.getenv("DIR_MATCHED")

# start_year should match the year of the ABCD data release
start_year <- as.numeric(Sys.getenv("PARAM_START_YEAR"))

## load input data----
# TODO: add to .env to allow for flexibility
advanced_company_indicators_sheet <- "Company Activities"

advanced_company_indicators_raw <- readxl::read_xlsx(
  path = input_path_advanced_company_indicators,
  sheet = advanced_company_indicators_sheet
)

company_ids_included <- readr::read_csv(
  input_path_split,
  col_types = readr::cols_only(
    company_id = "d"
  )
) %>%
  dplyr::pull(.data$company_id)


## calculate sector split----
advanced_company_indicators <- advanced_company_indicators_raw %>%
  janitor::clean_names() %>%
  dplyr::filter(
    .data$asset_sector %in% c("Coal", "Oil&Gas", "Power"),
    .data$activity_unit != "MW",
    .data$company_id %in% company_ids_included
  ) %>%
  dplyr::select(-c(starts_with("direct_ownership_"), starts_with("financial_control_"))) %>%
  dplyr::rename_with(.fn = ~ gsub("asset_", "", .x)) %>%
  tidyr::pivot_longer(
    cols = dplyr::starts_with("equity_ownership_"),
    names_to = "year",
    names_prefix = "equity_ownership_",
    values_to = "value",
    values_ptypes = list("value" = numeric())
  ) %>%
  dplyr::mutate(year = as.numeric(.data$year)) %>%
  dplyr::filter(.data$year == .env$start_year) %>%
  dplyr::mutate(
    sector = dplyr::case_when(
      .data$sector == "Coal" ~ "coal",
      .data$sector == "Oil&Gas" ~ "oil and gas",
      .data$sector == "Power" ~ "power",
      TRUE ~ .data$sector
    ),
    technology = dplyr::case_when(
      .data$sector == "coal" ~ "coal",
      .data$sector == "oil and gas" & grepl("Gas", .data$technology) ~ "gas",
      .data$sector == "oil and gas" & grepl("Oil", .data$technology) ~ "oil",
      .data$sector == "power" ~ tolower(.data$technology),
      TRUE ~ .data$technology
    )
  ) %>%
  dplyr::summarise(
    value = sum(.data$value, na.rm = TRUE),
    .by = c("company_id", "company_name", "sector", "technology", "activity_unit", "year")
  ) %>%
  dplyr::rename(
    name_company = "company_name",
    production = "value",
    production_unit = "activity_unit"
  )

primary_energy_efficiency <- get("primary_energy_efficiency")

unit_conversion <- get("unit_conversion")

sector_split_energy_companies <- advanced_company_indicators %>%
  get_energy_sector_split(
    start_year = start_year,
    primary_energy_efficiency = primary_energy_efficiency,
    unit_conversion = unit_conversion
  )

## write output----
sector_split_energy_companies %>%
  readr::write_csv(file.path(input_path_matched, "companies_sector_split.csv"))
