---
title: "Calculation of exposure-weighted aggregated alignment metric"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Calculation of exposure-weighted aggregated alignment metric}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
editor_options: 
  markdown: 
    wrap: 72
---

PACTA methodology note\
**Calculation of exposure-weighted aggregated alignment metric**

Prepared by Jacob Kastl

## 1. Background

### 1.1 The use case for exposure-weighted aggregated alignment metrics

The company alignment metric described in the previous chapter is the first building block needed to help make sense of alignment patterns in large analyses. This vignette describes how such company/sector level metrics can be aggregated to the loan book level to facilitate the identification of systemic patterns.

The aggregations described below can be made at any defined level of a loan book. More precisely, a loan book can be defined as anything between a sub selection of loans from one bank's loan book to the aggregated loan book of an entire PACTA sector across banks. Common levels of analysis will be:

(1) aggregations to the bank level, to facilitate bank-by-bank comparison and 
(2) aggregations to the bank group level, to understand patterns common to different types of financial institutions.

Any other level of analysis can be investigated too, using this same approach.


## 2. Exposure-weighted aggregated alignment metric

To obtain a loan book level aggregation of the company alignment metric, the portfolio weight approach is applied. The exposure weights for each company in the loan book are derived by dividing the loan value (drawn amount or debt outstanding) of a counterparty by the total loan value of the matched loan book. This assumes the drawn loan amount goes fully towards activity in the given sector.^[Company activity across multiple PACTA sectors can be taken into account using the following approach for [splitting loans in general](https://github.com/RMI-PACTA/workflow.aggregate.loanbooks#optional-calculate-sector-splits-for-multi-sector-energy-companies) and [production based splits for energy companies](https://github.com/RMI-PACTA/workflow.aggregate.loanbooks#methodological-note-sector-split-for-energy-companies).]

### 2.1 Defining exposure weights at the company/sector level

The exposure-weighted net (or buildout/phaseout) alignment for a given loan book is calculated as follows:

Loan exposure $l$ (debt outstanding) of bank (or loan book) $n$ to company $c$ in sector $b$, at time $t = 0$:

$$l_{n,b,c,t = 0}$$

### 2.2 Aggregating the company/sector level metric to the loan book by sector level

We derive the exposure-weighted company net alignment metric $Y$ at the by sector:

$$Y_{n,b,c,t} = \dfrac{l_{n,b,c,t=0}}{\sum_{b,c} l_{n,b,c,t=0}} \times y_{b,c,t}$$
Finally, the exposure-weighted net alignment metric $Y$ at the loan book by sector level follows as:

$$Y_{n,b,t} = \sum_{c} Y_{n,b,c,t} $$

Where applicable, we obtain the exposure-weighted buildout/phaseout-alignment metric for each company as:

$$Y_{n,b,c,d,t} = \dfrac{l_{n,b,c,t=0}}{\sum_{b,c} l_{n,b,c,t=0}} \times y_{b,c,d,t}$$

And correspondingly, the exposure-weighted buildout/phaseout-alignment metric can be calculated for the loan book level as:

$$Y_{n,b,d,t} = \sum_{c} Y_{n,b,c,d,t} $$

#### Interpretation:

The exposure-weighted net aggregate alignment metric $Y_{n,b,t}$ tells us if the activities of the companies that a loan book is exposed to in $t = 0$ are, on aggregate, aligned with the scenario-based values for each of the companies in $t = 5$. This should be read as a high-level summary of the alignment in a given loan book and is meant as a prompt for further analysis at more granular levels, especially as an entry into standard PACTA analysis and its metrics as laid out [here](https://rmi-pacta.github.io/r2dii.analysis/articles/r2dii-analysis.html).

Note that this value will be driven largely by the exposure to the relevant companies in the loan book. Hence, a positive value does not immediately imply the unweighted sum of the counterparties activities is aligned with a given scenario. Instead, the exposure-weighted result might be driven by one or more particularly well-performing companies, to which the loan book has significant exposures.

Note also that a disaggregation to the buildout and phaseout levels of the exposure-weighted aggregate alignment metric is necessary in sectors with both buildout and phaseout technologies, to understand the drivers of the net value. $Y_{n,b,d,t}$ provides this disaggregation. For unidirectional sectors, the disaggregation is equal to the net value and for emissions intensity based sectors that use the SDA approach, no disaggregation can be computed.
